---
# file: handlers/main.yml
#

- name: restart prometheus
  service: name=prometheus state=restarted
  when: prometheus_use_service|bool

- name: reload prometheus
  service: name=prometheus state=reloaded
  when: prometheus_use_service|bool

- name: stop prometheus
  service: name=prometheus state=stopped
  when: prometheus_use_service|bool


- name: restart node_exporter (systemd)
  systemd:
    state: restarted
    daemon_reload: yes
    name: node_exporter
  when: prometheus_node_exporter_use_systemd|bool

- name: restart node_exporter
  service: name=node_exporter state=restarted
  when: not prometheus_node_exporter_use_systemd|bool

- name: reload node_exporter
  service: name=node_exporter state=reloaded

- name: stop node_exporter
  service: name=node_exporter state=stopped



- name: restart alertmanager
  service: name=alertmanager state=restarted
  when: prometheus_use_service|bool

- name: reload alertmanager
  service: name=alertmanager state=reloaded
  when: prometheus_use_service|bool

- name: stop alertmanager
  service: name=alertmanager state=stopped
  when: prometheus_use_service|bool
